
(nyvenv) C:\Users\udayp\DatabaseStoreManager>python manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\udayp\DatabaseStoreManager\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Users\udayp\DatabaseStoreManager\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\udayp\DatabaseStoreManager\nyvenv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\udayp\DatabaseStoreManager\nyvenv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\udayp\DatabaseStoreManager\nyvenv\Lib\site-packages\django\core\management\base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\udayp\DatabaseStoreManager\nyvenv\Lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "C:\Users\udayp\DatabaseStoreManager\nyvenv\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "C:\Users\udayp\DatabaseStoreManager\nyvenv\Lib\site-packages\django\core\management\commands\makemigrations.py", line 159, in handle
    loader.check_consistent_history(connection)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\udayp\DatabaseStoreManager\nyvenv\Lib\site-packages\django\db\migrations\loader.py", line 327, in check_consistent_history
    raise InconsistentMigrationHistory(
    ...<8 lines>...
    )
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency Tenant.0001_initial on database 'default'.

(nyvenv) C:\Users\udayp\DatabaseStoreManager>